apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraping-database
spec:
  selector:
    matchLabels:
      app: scraping-database
  replicas: 1
  template:
    metadata:
      labels:
        app: scraping-database
    spec:
      containers:
        - name: postgres
          image: gcr.io/full-stack-ml-challenge/my-postgres:v1
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_HOST
              value: localhost
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: postgresdb
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/postgresql/data
      imagePullSecrets:
        - name: gcr-json-key
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: scraping-database
spec:
  selector:
    app: scraping-database
  ports:
    - port: 5432
      targetPort: 5432
