apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-env-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-env
spec:
  selector:
    matchLabels:
      app: python-env
  replicas: 1
  template:
    metadata:
      labels:
        app: python-env
    spec:
      containers:
        - name: python
          image: gcr.io/full-stack-ml-challenge/python-poetry:latest
          command:
            - jupyter
            - lab
            - --no-browser
            - --ip=0.0.0.0
            - --port=8787
            - --allow-root
          env:
            - name: POSTGRES_HOST
              value: scraping-database
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: postgresdb
          ports:
            - containerPort: 8787
          volumeMounts:
            - name: notebooks-volume
              mountPath: /home/fullstack_ml/notebooks
      imagePullSecrets:
        - name: gcr-json-key
      volumes:
        - name: notebooks-volume
          persistentVolumeClaim:
            claimName: python-env-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: python-env
spec:
  selector:
    app: python-env
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8787
      targetPort: 8787
