apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-streamer
  template:
    metadata:
      labels:
        app: reddit-streamer
    spec:
      initContainers:
        - name: wait-for-service
          image: busybox
          command: ['sh', '-c', 'until nc -z "kafka:9092"; do echo waiting for service; sleep 2; done']
      containers:
        - name: reddit-streamer
          image: southamerica-east1-docker.pkg.dev/reddit-sentiment-stream-441421/reddit-sentiment-stream/reddit-streamer:latest
          command: ["python", "src/streamer/reddit_streamer.py"]
          env:
            - name: KAFKA_SERVER
              value: "kafka:9092"
            - name: GOOGLE_APPLICATION_CREDENTIALS_JSON
              valueFrom:
                secretKeyRef:
                  name: gcp-service-account
                  key: gcp-credentials.json
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: reddit-streamer
spec:
  selector:
    app: reddit-streamer
  ports:
    - port: 8080
      targetPort: 8080
